BOT_TOKEN = "Insert Bot Token Here."
CHANNEL_ID = "Insert Channel ID Here."
COMMAND_PREFIX = "Insert Command Prefix Here."
BOT_DESCRIPTION = "Insert Bot Description Here."
TWITTER_API_KEY = ""
TWITTER_API_S = ""
TWITTER_ACCESS_TOKEN = ""
TWITTER_ACCESS_TOKEN_S = ""
